import type { Metadata } from "next";

import "./globals.css";
import Footer from "@/components/Footer"
import HeaderComp from "@/components/HeaderComp";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased flex flex-col min-h-screen"
      >
      <HeaderComp />
        <main className="flex-1 mt-20">
        
        {children}
        </main>
        <Footer />
      </body>
   
    </html>
  );
}
